//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conversion.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Conversion.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string temperature {
            get {
                return ResourceManager.GetString("temperature", resourceCulture);
            }
        }
        
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        internal static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        internal static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        internal static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        internal static string bit {
            get {
                return ResourceManager.GetString("bit", resourceCulture);
            }
        }
        
        internal static string _byte {
            get {
                return ResourceManager.GetString("byte", resourceCulture);
            }
        }
        
        internal static string kilobit {
            get {
                return ResourceManager.GetString("kilobit", resourceCulture);
            }
        }
        
        internal static string kibibit {
            get {
                return ResourceManager.GetString("kibibit", resourceCulture);
            }
        }
        
        internal static string kilobyte {
            get {
                return ResourceManager.GetString("kilobyte", resourceCulture);
            }
        }
        
        internal static string kibibyte {
            get {
                return ResourceManager.GetString("kibibyte", resourceCulture);
            }
        }
        
        internal static string megabit {
            get {
                return ResourceManager.GetString("megabit", resourceCulture);
            }
        }
        
        internal static string mebibit {
            get {
                return ResourceManager.GetString("mebibit", resourceCulture);
            }
        }
        
        internal static string megabyte {
            get {
                return ResourceManager.GetString("megabyte", resourceCulture);
            }
        }
        
        internal static string mebibyte {
            get {
                return ResourceManager.GetString("mebibyte", resourceCulture);
            }
        }
        
        internal static string gigabit {
            get {
                return ResourceManager.GetString("gigabit", resourceCulture);
            }
        }
        
        internal static string gibibit {
            get {
                return ResourceManager.GetString("gibibit", resourceCulture);
            }
        }
        
        internal static string gigabyte {
            get {
                return ResourceManager.GetString("gigabyte", resourceCulture);
            }
        }
        
        internal static string gibibyte {
            get {
                return ResourceManager.GetString("gibibyte", resourceCulture);
            }
        }
        
        internal static string terabit {
            get {
                return ResourceManager.GetString("terabit", resourceCulture);
            }
        }
        
        internal static string tebibit {
            get {
                return ResourceManager.GetString("tebibit", resourceCulture);
            }
        }
        
        internal static string terabyte {
            get {
                return ResourceManager.GetString("terabyte", resourceCulture);
            }
        }
        
        internal static string tebibyte {
            get {
                return ResourceManager.GetString("tebibyte", resourceCulture);
            }
        }
        
        internal static string petabit {
            get {
                return ResourceManager.GetString("petabit", resourceCulture);
            }
        }
        
        internal static string pebibit {
            get {
                return ResourceManager.GetString("pebibit", resourceCulture);
            }
        }
        
        internal static string petabyte {
            get {
                return ResourceManager.GetString("petabyte", resourceCulture);
            }
        }
        
        internal static string pebibyte {
            get {
                return ResourceManager.GetString("pebibyte", resourceCulture);
            }
        }
        
        internal static string exabit {
            get {
                return ResourceManager.GetString("exabit", resourceCulture);
            }
        }
        
        internal static string exbibit {
            get {
                return ResourceManager.GetString("exbibit", resourceCulture);
            }
        }
        
        internal static string exabyte {
            get {
                return ResourceManager.GetString("exabyte", resourceCulture);
            }
        }
        
        internal static string exbibyte {
            get {
                return ResourceManager.GetString("exbibyte", resourceCulture);
            }
        }
    }
}
