//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conversion.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Conversion.Resx.AppResources.es", typeof(AppResources_es).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string temperature {
            get {
                return ResourceManager.GetString("temperature", resourceCulture);
            }
        }
        
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        internal static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        internal static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        internal static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        internal static string bit {
            get {
                return ResourceManager.GetString("bit", resourceCulture);
            }
        }
        
        internal static string _byte {
            get {
                return ResourceManager.GetString("byte", resourceCulture);
            }
        }
        
        internal static string kilobyte {
            get {
                return ResourceManager.GetString("kilobyte", resourceCulture);
            }
        }
        
        internal static string megabyte {
            get {
                return ResourceManager.GetString("megabyte", resourceCulture);
            }
        }
        
        internal static string gigabyte {
            get {
                return ResourceManager.GetString("gigabyte", resourceCulture);
            }
        }
        
        internal static string terabyte {
            get {
                return ResourceManager.GetString("terabyte", resourceCulture);
            }
        }
        
        internal static string petabyte {
            get {
                return ResourceManager.GetString("petabyte", resourceCulture);
            }
        }
        
        internal static string exabyte {
            get {
                return ResourceManager.GetString("exabyte", resourceCulture);
            }
        }
        
        internal static string zettabyte {
            get {
                return ResourceManager.GetString("zettabyte", resourceCulture);
            }
        }
        
        internal static string yottabyte {
            get {
                return ResourceManager.GetString("yottabyte", resourceCulture);
            }
        }
    }
}
